name: Test add mask
on:
  push:
    branches:
      - "**"

jobs:
  simple-add-mask:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check not masked
        run: echo "${SECRET_TEXT}"
        env:
          SECRET_TEXT: 'ultra super secret'

      - name: Add mask
        run: |
          cat add_mask.txt secret_text.txt
          echo ""

      - name: Check masked
        run: echo "${SECRET_TEXT}"
        env:
          SECRET_TEXT: 'ultra super secret'

  check-in-other-job:
    needs: simple-add-mask
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check
        run: echo "${SECRET_TEXT}"
        env:
          SECRET_TEXT: 'ultra super secret'

  anti-add-mask:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set secet text to outputs
        id: get_secret
        run: echo '::set-output name=SECRET_TEXT::ultra super secret'

      - name: Add mask
        run: echo "::add-mask::$SECRET_TEXT"
        env:
          SECRET_TEXT: ${{ steps.get_secret.outputs.SECRET_TEXT}}

      - name: Check masked
        run: echo 'ultra super secret'

