name: Test add mask
on:
  push:
    branches:
      - "**"

jobs:
  simple-add-mask:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check not masked
        run: cat secret_text.txt

      - name: Add mask
        run: |
          echo -n '::add-mask::' > cmd.txt
          cat secret_text.txt >> cmd.txt
          cat cmd.txt
          rm cmd.txt

      - name: Check masked
        run: cat secret_text.txt

  check-in-other-job:
    needs: simple-add-mask
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check
        run: echo 'ultra super secret'

  anti-add-mask:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set secet text to outputs
        id: get_secret
        run: echo '::set-output name=SECRET_TEXT::ultra super secret'

      - name: Add mask
        run: echo "::add-mask::$SECRET_TEXT"
        env:
          SECRET_TEXT: ${{ steps.get_secret.outputs.SECRET_TEXT}}

      - name: Check masked
        run: echo 'ultra super secret'

  use-in-other-command:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check not masked
        run: echo -n 'ultra super secret' | sha256sum

      - name: Set secet text to outputs
        id: out_not_masked
        run: echo '::set-output name=SECRET_TEXT::ultra super secret'

      - name: Check outputs
        run: echo -n "${SECRET_TEXT}" | sha256sum
        env:
          SECRET_TEXT: ${{ steps.out_not_masked.outputs.SECRET_TEXT}}

      - name: Add mask
        run: |
          echo -n '::add-mask::' > cmd.txt
          cat secret_text.txt >> cmd.txt
          cat cmd.txt
          rm cmd.txt

      - name: Set secet text to outputs
        id: out_masked
        run: echo '::set-output name=SECRET_TEXT::ultra super secret'

      - name: Check outputs
        run: echo -n "${SECRET_TEXT}" | sha256sum
        env:
          SECRET_TEXT: ${{ steps.out_masked.outputs.SECRET_TEXT}}

  split-by-blank:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check not masked
        run: echo 'ultra super secret'

      - name: Add mask
        run: |
          echo -n '::add-mask::' > cmd.txt
          cat secret_text.txt >> cmd.txt
          cat cmd.txt
          rm cmd.txt

      - name: Check masked
        run: echo 'ultra super secret'

      - name: Check with blank
        run: echo 'start ultra super secret end'

      - name: Check without blank
        run: echo 'startultra super secretend'

      - name: Check with quote
        run: echo '"ultra super secret"'

      - name: Check each words
        run: echo 'ultra A super B secret'

      - name: Check each words(multi lines)
        run: | 
          echo 'ultra'
          echo '-- separator --'
          echo 'super'
          echo '-- separator --'
          echo 'secret'

