name: Test add mask
on:
  push:
    branches:
      - "**"

jobs:
  simple-add-mask:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check not masked
        run: cat secret_text.txt

      - name: Add mask
        run: |
          echo -n '::add-mask::' > cmd.txt
          cat secret_text.txt >> cmd.txt
          cat cmd.txt
          rm cmd.txt

      - name: Check masked
        run: cat secret_text.txt

  check-in-other-job:
    needs: simple-add-mask
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check
        run: echo 'ultra super secret'

  anti-add-mask:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set secet text to outputs
        id: get_secret
        run: echo '::set-output name=SECRET_TEXT::ultra super secret'

      - name: Add mask
        run: echo "::add-mask::$SECRET_TEXT"
        env:
          SECRET_TEXT: ${{ steps.get_secret.outputs.SECRET_TEXT}}

      - name: Check masked
        run: echo 'ultra super secret'

